# GitHub Stars are like dev's money. Support us with stars ☆☆☆☆☆ !

People who want to make the other types of support,
are free to message their proposed form of support.

Code adoptions and contributions are the best kind of support !
